platform :ios, '8.0'

target 'SmartClass' do
    use_frameworks!

    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'


    pod 'GCDWebServer/WebUploader', '~> 3.3.3'
    pod 'Reachability', '~> 3.2'

    pod 'Toast', '~> 3.0'
    pod 'DZNEmptyDataSet', '~> 1.7.3'
    pod 'IQKeyboardManager', '~> 4.0.7'
    pod 'VideoCore', '~> 0.3.2’
end

