platform :ios, '8.0'
use_frameworks!

target 'SmartClass' do
    use_frameworks!

    pod 'IQKeyboardManager'
    pod 'ReactiveCocoa', '~> 4.1.0'
    pod 'Toast', '~> 3.0'
    pod 'DZNEmptyDataSet', '~> 1.7.3'
    pod 'SnapKit', '~> 0.20.0'
    pod 'GCDWebServer/WebUploader', '~> 3.3.2'

end

